# Generated by Django 3.1.2 on 2020-10-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktype',
            old_name='description',
            new_name='tasktype_description',
        ),
    ]
